retrieve_news_task:
  description: >
    Search and retrieve the most recent and relevant news articles about {topic}.
  expected_output: >
    A list of 5-10 headlines with short summaries and source links, all related to {topic}.
  agent: retrieve_news

website_scrape_task:
  description: >
    Extract and summarize key information from various websites related to {topic}.
  expected_output: >
    A summary of the most relevant information extracted from the websites, including
    key points and insights related to {topic}.
  agent: website_scraper

ai_news_write_task:
  description: >
    Generate a comprehensive and engaging news article based on the information gathered.
  expected_output: >
    A well-structured news article that captures the essence of the information gathered,
    including a catchy headline, introduction, body, and conclusion.
  agent: ai_news_writer

file_writer_task:
  description: >
    Organize and write clean, well-structured files based on content.
  expected_output: >
    A fully fledge news article with all information from previous task into a file named news/{date}_news_article.md
  agent: file_writer